title: Open Wine Maps
description: A repository for global wine related geophraphical artificats. 
theme: just-the-docs

url: https://openwinemaps.org

aux_links:
  # Open Wine Project: https://openwineproject.org
  Project Repository: https://github.com/OpenWineProject/openwinemaps

# plugins:
  # - jekyll-leaflet

# collections:
#   maps:
#    permalink: "/:collection/:path"
#    output: true

# just_the_docs: 
#   collections:
#     maps:
#       name: Maps
