title: Open Wine Maps
description: A repository for global wine related geophraphical artificats. 
theme: just-the-docs

url: https://openwinemaps.org

ga_tracking: G-037QKQY0BY
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

aux_links:
  Open Wine Project: https://openwineproject.org
  Project Repository: https://github.com/OpenWineProject/openwinemaps

# plugins:
#   - jekyll-sqlite

# sqlite:
#   - data: countries
#     file: _db/openwinemaps.sqlite3
#     query: SELECT * FROM productionByCountry ORDER by ProductionInTonnes DESC

# collections:
#   maps:
#    permalink: "/:collection/:path"
#    output: true

# just_the_docs: 
#   collections:
#     maps:
#       name: Maps
